# Zola configuration for Rainmatter Foundation

base_url = "https://rainmatter.org"
title = "Rainmatter Foundation"
description = "Non-profit working on environment, climate change, green livelihood projects in India."
default_language = "en"
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = false

[markdown]
highlight_code = false
smart_punctuation = false

[extra]
subtitle = "Non-profit working on environment, climate change, green livelihood projects in India."

# Menu configuration
[[extra.menu]]
name = "About"
url = "/about"
weight = 1

[[extra.menu]]
name = "Partners"
url = "/partners"
weight = 2

[[extra.menu]]
name = "Place Thesis"
url = "/place-thesis"
weight = 3

[[extra.menu]]
name = "Focus Areas"
url = "/focus-areas"
weight = 4

[[extra.menu]]
name = "Blog"
url = "https://blog.rainmatter.org"
weight = 5

[[extra.menu]]
name = "Forum"
url = "https://grove.rainmatter.org"
weight = 6
